version: 0.2

phases:
  install:
    runtime-versions:
      nodejs:22
    commands:
    - echo Installing source NPM dependencies..
    - npm install
  builds:
    commands:
    - echo Build started on 'date'
    - echo Building the node.js application...
    - echo run Build
  post_build:
    commands:
      - echo Build completed on 'date'

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
  