version: 0.2

phases:
  install:
    runtime-versions:
      nodejs:22
    commands:
    - echo Installing source NPM dependencies..
    - npm install
  builds:
    commands:
    - echo Build started on 'date'
    - echo Building the node.js application...
    - echo run Build
  post_build:
    commands:
      - echo Build completed on 'date'
      - mkdir deploy
      - cp -r dist deploy/dist
      - cp appspec.yaml appspec.yml
      - cp appspec.yml deploy
      - cp -r scripts deploy/
      - chmod +x deploy/scripts/restartNginx.sh
      - chmod +x deploy/scripts/appstop.sh


artifacts:
  files:
    - '**/*'
  base-directory: deploy
  name: frontend-build
