services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: gopal
      MYSQL_PASSWORD: gopal123
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: vinayakprajapati123/backend:v1
    container_name: backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"

  frontend:
    image: vinayakprajapati123/frontend:v1
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
volumes:
  mysql_data: